version: "3"

services:
  insight:
    build:
      context: .
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 3001:3001
      - 1989:1989
    volumes:
      - ./data/:/bitcoinz/data
    # The following can be used if you want to use port 80 for the api instead
    # of 3001. Change 3001:3001 above to just 3001 and uncomment the below.
    # This uses https://github.com/jwilder/nginx-proxy and
    # https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
    # environment:
    #   - VIRTUAL_HOST=explorer.btcz.rocks
    #   - LETSENCRYPT_HOST=explorer.btcz.rocks
    #   - LETSENCRYPT_EMAIL=contact@btcz.rocks
